# Generated by Django 2.0.3 on 2018-03-30 10:02

from django.db import migrations, models
import django.db.models.deletion
import puzzle.models


class Migration(migrations.Migration):

    replaces = [('puzzle', '0001_initial'), ('puzzle', '0002_auto_20180327_1518'), ('puzzle', '0003_parts_most_far_distance'), ('puzzle', '0004_auto_20180330_1140'), ('puzzle', '0005_auto_20180330_1334'), ('puzzle', '0006_puzzle_is_test')]

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Parts Name')),
                ('x', models.FloatField(verbose_name='X')),
                ('y', models.FloatField(verbose_name='Y')),
                ('img', models.FileField(upload_to=puzzle.models.get_image_path, verbose_name='Image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Puzzle Name')),
                ('bg_image', models.ImageField(upload_to=puzzle.models.get_image_path, verbose_name='BackGround')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('for_begginer', models.BooleanField(default=True, verbose_name='Beginner')),
                ('is_test', models.BooleanField(default=True, verbose_name='Is Test')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='parts',
            name='puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='puzzle.Puzzle'),
        ),
        migrations.AddField(
            model_name='parts',
            name='ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Ratio'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='img',
            field=models.ImageField(upload_to=puzzle.models.get_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='x',
            field=models.FloatField(default=0.0, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='y',
            field=models.FloatField(default=0.0, verbose_name='Y'),
        ),
        migrations.AddField(
            model_name='parts',
            name='most_far_distance',
            field=models.FloatField(default=0.0, verbose_name='Most far distance'),
        ),
    ]
