version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.app
    env_file:
      - ./docker/app/.env
    volumes:
      - ./src/kit_campus_puzzle:/opt/kit_campus_puzzle
    ports:
      - '8000:8000'
    command: python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    links:
      - db
  db:
    image: studioaquatan/mysql-utf8mb4:latest
    ports:
      - '3306:3306'
    env_file:
      - ./docker/mysql/.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
